M48
; DRILL file {KiCad 9.0.7} date 2026-09-14T18:50:18-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T18:50:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X4.0Y-15.179
T2
X4.0Y-18.25
X4.0Y-21.0
X4.0Y-23.75
T3
X21.0Y-2.571
X21.0Y-5.111
X21.0Y-7.651
T4
X4.0Y-3.0
X4.0Y-29.0
M30
