(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Excite_V1-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 22 April 2026 at 12:08)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.85)
(Tool: 2 -> Dia: 1.143)
(Tool: 3 -> Dia: 1.2)
(Tool: 4 -> Dia: 2.7)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 25.0)
(Tool: 2 -> Feedrate: 25.0)
(Tool: 3 -> Feedrate: 25.0)
(Tool: 4 -> Feedrate: 25.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)
(Tool: 4 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)
(Tool: 3 -> Offset Z: 0.0)
(Tool: 4 -> Offset Z: 0.0)

(DEPTH_PER_CUT: )
(Tool: 1 -> DeptPerCut: 0.6)
(Tool: 2 -> DeptPerCut: 0.6)
(Tool: 3 -> DeptPerCut: 0.6)
(Tool: 4 -> DeptPerCut: 0.6)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Excellon: Default_no_M6)

(X range:    1.8995 ...   42.3495  mm)
(Y range:    1.6495 ...   41.9245  mm)

(Spindle Speed: 10000 RPM)
G21
G90
G94

G01 F25.00

M5
G00 Z15.0000
T1
G00 X0.0000 Y0.0000                
(MSG, Change to Tool Dia = 0.8500 ||| Total drills for tool T1 = 10)
M0
G00 Z15.0000
        
G01 F25.00
M03 S10000
G00 X11.4995 Y41.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X40.9995 Y2.9995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X40.9995 Y39.9995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X3.4995 Y2.9995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X3.4995 Y39.9995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X2.4995 Y19.1965
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X31.7575 Y38.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X29.2175 Y38.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X26.6775 Y38.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X11.4995 Y38.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


