(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Untitled-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 06 May 2026 at 09:32)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.0)
(Tool: 2 -> Dia: 1.524)
(Tool: 3 -> Dia: 2.7)
(Tool: 4 -> Dia: 3.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 25.0)
(Tool: 3 -> Feedrate: 25.0)
(Tool: 4 -> Feedrate: 25.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)
(Tool: 2 -> Z_Cut: -2.0)
(Tool: 3 -> Z_Cut: -2.0)
(Tool: 4 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)
(Tool: 3 -> Offset Z: 0.0)
(Tool: 4 -> Offset Z: 0.0)

(DEPTH_PER_CUT: )
(Tool: 1 -> DeptPerCut: 0.7)
(Tool: 2 -> DeptPerCut: 0.6)
(Tool: 3 -> DeptPerCut: 0.6)
(Tool: 4 -> DeptPerCut: 0.6)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Excellon: Default_no_M6)

(X range:    1.9995 ...   63.0235  mm)
(Y range:    1.1495 ...   29.8495  mm)

(Spindle Speed: 10000 RPM)
G21
G90
G94

G01 F25.00

M5
G00 Z15.0000
T2
G00 X0.0000 Y0.0000                
(MSG, Change to Tool Dia = 1.5240 ||| Total drills for tool T2 = 10)
M0
G00 Z15.0000
        
G01 F25.00
M03 S10000
G00 X22.7645 Y24.0725
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X57.4995 Y7.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X27.5275 Y23.5015
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X61.4995 Y2.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X61.4995 Y28.4995
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X3.4995 Y2.7245
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X3.4995 Y28.0935
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X62.2615 Y6.9275
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X62.2615 Y24.0725
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.7645 Y6.9275
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.0000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


