(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Untitled-F_Cu.gbr_iso_combined_cutout_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 15 April 2026 at 12:44)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)

(TOOL DIAMETER: 1.0 mm)
(Feedrate_XY: 100.0 mm/min)
(Feedrate_Z: 25.0 mm/min)
(Feedrate rapids 1500.0 mm/min)

(Z_Cut: -1.8 mm)
(Z_Move: 2.0 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Geometry: Default_no_M6)

(X range:   -0.1376 ...   79.1366  mm)
(Y range:   -0.1376 ...   29.1366  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G94

G01 F100.00

M5
G00 Z15.0000
G00 X0.0000 Y0.0000
T1
(MSG, Change to Tool Dia = 1.0000)
M0
G00 Z15.0000
        
M03 S10000.0
G01 F100.00
G00 X-0.1376 Y14.4995
G01 F25.00
G01 Z-1.8000
G01 F100.00
G01 X-0.1376 Y-0.1376
G01 X79.1366 Y-0.1376
G01 X79.1366 Y14.4995
G00 Z2.0000
G00 X-0.1376 Y18.4995
G01 F25.00
G01 Z-1.8000
G01 F100.00
G01 X-0.1376 Y29.1366
G01 X79.1366 Y29.1366
G01 X79.1366 Y18.4995
G00 Z2.0000
M05
G00 Z2.0000
G00 Z15.00


