(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Excite_V1-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Tuesday, 08 September 2026 at 16:38)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.85)
(Tool: 2 -> Dia: 1.143)
(Tool: 3 -> Dia: 1.2)
(Tool: 4 -> Dia: 2.7)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 25.0)
(Tool: 2 -> Feedrate: 25.0)
(Tool: 3 -> Feedrate: 25.0)
(Tool: 4 -> Feedrate: 25.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)
(Tool: 4 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)
(Tool: 3 -> Offset Z: 0.0)
(Tool: 4 -> Offset Z: 0.0)

(DEPTH_PER_CUT: )
(Tool: 1 -> DeptPerCut: 0.6)
(Tool: 2 -> DeptPerCut: 0.6)
(Tool: 3 -> DeptPerCut: 0.6)
(Tool: 4 -> DeptPerCut: 0.6)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Excellon: Default_no_M6)

(X range:    2.6750 ...   42.8750  mm)
(Y range:    2.6750 ...   31.3750  mm)

(Spindle Speed: 10000 RPM)
G21
G90
G94

G01 F25.00

M5
G00 Z15.0000
T1
G00 X0.0000 Y0.0000                
(MSG, Change to Tool Dia = 0.8500 ||| Total drills for tool T1 = 11)
M0
G00 Z15.0000
        
G01 F25.00
M03 S10000
G00 X4.0250 Y15.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X41.5250 Y4.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X41.5250 Y30.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X4.0250 Y4.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X4.0250 Y30.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X4.0250 Y12.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X21.0250 Y25.3740
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X21.0250 Y27.9140
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X21.0250 Y30.4540
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X12.0250 Y30.5250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
G00 X4.0250 Y9.0250
G01 Z-0.6000
G01 Z0
G00 Z2.0000
G01 Z-1.2000
G01 Z0
G00 Z2.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 Z-2.4000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


