M48
; DRILL file {KiCad 9.0.7} date 2026-04-15T11:55:58-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-15T11:55:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.143
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X12.0Y-3.0
X12.0Y-6.0
T2
X27.178Y-6.0
X29.718Y-6.0
X32.258Y-6.0
T3
X3.0Y-25.303
T4
X4.0Y-4.5
X4.0Y-41.5
X41.5Y-4.5
X41.5Y-41.5
M30
